"""Deterministic synthetic fixture, for software verification and demonstrations only."""
from pathlib import Path
import json
import numpy as np
import xarray as xr
from .science import Model, VARIABLES, normalize
from .analysis import compare, coverage
from .diagnostics import diagnose_model, diagnose_observation
from .reference import load_reference
from .incois import load_incois

def build_demo():
    lon=np.linspace(80,94,34);lat=np.linspace(6,22,36);depth=np.linspace(0,1000,25)
    dates=np.arange(np.datetime64('2025-09-01'),np.datetime64('2025-09-07'))
    t,z,y,x=np.meshgrid(np.arange(6),depth,lat,lon,indexing='ij')
    eddy=np.exp(-((x-87-t*.18)**2+(y-14)**2)/7)
    thermo=120+90*eddy+25*np.sin((y-8)/4+t*.25)
    temp=6+23*np.exp(-z/(thermo+180))+0.6*np.sin(x/2+t*.3)*np.exp(-z/150)
    sal=35.1-1.9*np.exp(-z/80)*np.clip((y-6)/16,0,1)+.2*eddy
    u=-(y-14)*.18*eddy*np.exp(-z/550)+.08*np.sin(y*.5+t*.5)*np.exp(-z/250)
    v=(x-87-t*.18)*.18*eddy*np.exp(-z/550)
    chl=.04+.9*np.exp(-((z-65)/50)**2)*(1+.6*eddy)
    # Deliberately simplified analytic land mask; not authoritative bathymetry/coastline.
    wet=(x>80+.23*np.maximum(y-12,0)) & ~((x>92.7)&(y>18))
    data={k:(('time','depth','latitude','longitude'),np.where(wet,a,np.nan).astype('float32'),dict(units={'temperature':'degree_Celsius','salinity':'1','u':'m s-1','v':'m s-1','chlorophyll':'mg m-3'}[k],standard_name=VARIABLES[k]['standard'])) for k,a in zip(VARIABLES,[temp,sal,u,v,chl])}
    ds=xr.Dataset(data,coords=dict(time=dates,depth=('depth',depth,{'units':'m','positive':'down'}),latitude=lat,longitude=lon),attrs={'Conventions':'CF-1.10','title':'Bay of Bengal analytic demonstration','synthetic':'true'})
    provenance=dict(title=ds.attrs['title'],synthetic=True,source='Deterministic analytic field generated by Ocean3D',version='demo-v1',license='Repository license',warning='Synthetic model and instruments. Not INCOIS or Copernicus observations; not an operational forecast.')
    model=Model('demo-bob',normalize(ds),provenance)
    profiles=[]
    for i,(name,instrument,lo,la) in enumerate([('DEMO-ARGO-01','Argo',85.2,14.8),('DEMO-ARGO-02','Argo',88.6,17.4),('DEMO-GLIDER-01','Glider',83.8,11.2),('DEMO-CTD-01','CTD',89.4,10.2),('DEMO-BGC-01','BGC Argo',87.1,13.2),('DEMO-ARGO-03','Argo',90.3,19.4)]):
        date='2025-09-03T12:00:00Z';rows=[]
        for variable in ('temperature','salinity','chlorophyll'):
            zz=np.array([10,25,50,75,100,150,200,300,400,500,650,800,950])
            predicted=model.sample(variable,lo,la,zz,date.replace('Z',''))
            for j,(d,val) in enumerate(zip(zz,predicted)):
                perturb=(.4 if variable=='temperature' else .08)*np.sin(j*.7+i)+(.35 if i==0 and variable=='temperature' else .03)
                rows.append(dict(depth=int(d),variable=variable,value=round(float(val+perturb),5),qc=4 if j==7 else (2 if j==3 else 1),adjusted=True,error=.01 if variable=='temperature' else .02))
        profiles.append(dict(id=name,instrument=instrument,longitude=lo,latitude=la,time=date,data_mode='D (simulated)',source='Analytic demonstration fixture',synthetic=True,samples=rows,depth_range=[10,950]))
    return model,profiles

def export():
    from .api import ROOT
    root=ROOT/'web'/'public'/'demo';root.mkdir(parents=True,exist_ok=True)
    model,profiles=build_demo()
    cases=[(model,profiles)]
    reference=load_reference()
    if reference: cases.append(reference)
    incois=load_incois()
    if incois: cases.insert(0,incois)
    all_profiles=[p for _,items in cases for p in items]
    def write(name,obj): (root/name).write_text(json.dumps(obj,separators=(',',':'),allow_nan=False),encoding='utf-8')
    write('catalog.json',{'models':[m.catalog() for m,_ in cases],'profiles':[{k:v for k,v in p.items() if k!='samples'} for p in all_profiles],'mode':'bundled-data'})
    write('profiles.json',all_profiles)
    diagnostics={};comparisons={};coverages={}
    for m,_ in cases:
        (root/m.id).mkdir(exist_ok=True)
        for variable in m.ds.data_vars:
            for index in range(m.ds.sizes['time']):
                write(f'{m.id}/{variable}-{index}.json',m.volume(variable,index))
                if float(m.ds.depth.min())<500:
                    write(f'{m.id}/{variable}-{index}-upper500.json',m.volume(variable,index,maximum_depth=500))
        for p in all_profiles:
            for v in m.ds.data_vars:
                for qc in ('strict','lenient'): comparisons[f'{m.id}:{p["id"]}:{v}:{qc}']=compare(m,p,v,qc)
            for index in range(m.ds.sizes['time']):
                if not {'temperature','salinity'}.issubset(m.ds): continue
                result=diagnose_model(m,p['longitude'],p['latitude'],index)
                try: result['observation']=diagnose_observation(p)
                except ValueError as exc: result['observation_unavailable']=str(exc)
                diagnostics[f'{m.id}:{p["id"]}:{index}']=result
        for v in m.ds.data_vars:
            for i in range(m.ds.sizes['time']):
                for qc in ('strict','lenient'): coverages[f'{m.id}:{v}:{i}:{qc}']=coverage(m,all_profiles,v,i,qc)
    write('comparisons.json',comparisons)
    write('coverage.json',coverages)
    write('diagnostics.json',diagnostics)
    data=ROOT/'data';data.mkdir(exist_ok=True)
    model.ds.to_netcdf(data/'demo-model.nc')
    import csv
    with (data/'example-profiles.csv').open('w',newline='',encoding='utf-8') as f:
        writer=csv.DictWriter(f,fieldnames=['profile_id','instrument','longitude','latitude','time','depth','variable','value','qc','adjusted','error','data_mode','synthetic'])
        writer.writeheader()
        for p in profiles:
            for r in p['samples']:
                writer.writerow(dict(profile_id=p['id'],**{k:p[k] for k in ['instrument','longitude','latitude','time','data_mode','synthetic']},**r))
    print('Exported deterministic demo, NetCDF and CSV fixtures.')

if __name__=='__main__': export()
